# -*- coding: utf-8 -*-
"""Números aleatórios.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1czd7xpTaNkzXhtEeW4d46-yB2mjZwDJ_
"""

from math import *
from random import *
import matplotlib.pyplot as plt
import numpy as np

seed = 321659

def randi(a = 1029,b = 221591,c = 1048576):
	global seed
	a = 1029; b = 221591; c = 1048576
	seed = (seed*a + b)%c
	return float(seed)/c

def roleta():
  return int(37*randi())

def dado():  
  return int(6*randi()) + 1

def moeda():
  return 2*int(2*randi()) - 1

N = 1000
walk = 0
for t in range (1 , N ) :
  walk += moeda ()

#pesquisa de voto
N = 1000
p = 1
def binom ( p ) :
  x = 0
  if randi () < p :
    x = 1
  return x

count = 0
for t in range (1 , N ) :
  count += binom (p)

# algoritmo da caixa
N = 1000
box = [ -1]* N ; Nd = 0
for j in range (1 , t +1) :
  i = int ( N * random () )
  box [ i ] = - box [ i ]
  Nd += box [ i ]

# plotando as probabilidades
N = 10000000
lancamentos = []
for i in range(N):
  lancamentos.append(dado())
a = np.array(lancamentos)
fig, ax = plt.subplots(figsize =(10, 7)) 
ax.hist(a, bins = [1,2,3,4,5,6,7]) 
plt.show()